---
- name: Calling the OmniSci module from ansible
  hosts: localhost

  vars:
    platform: "spc"
    group: nrb
    new: yes

  tasks:
  - name: Call OmniSci
    omnisci:
      platform: "{{ platform }}"
      group: "{{ group }}"
    register: results

  - name: omnisci results
    debug:
      var: results
